### ISSUE TITLE
HDRmaxFilter.swift:23: Fatal error: Unable to create color kernel

### ISSUE THREAD

**Issue by macdavis** [chemharuka/toGainMapHDR#5]
Issue happened when using -p, macOS verson: 15.3.

Kindly let me know if you need more information. Thanks!

**Comment by chemharuka** [comment]
Yes, I need more informations.

Did you download the metal files in same folder as contains toGainMapHDR
file?

**Comment by macdavis** [comment]
Yes. I used this command `git clone https://github.com/chemharuka/toGainMapHDR.git ` to download

**Comment by chemharuka** [comment]
May I have some sample photo files that have issue?

**Comment by macdavis** [comment]
I tried your sample photo, DJI_1_0226_D.heic, and has the same issue.

**Comment by chemharuka** [comment]
Works fine on my mac (15.3).
Do you have Xcode Command line tool (Xcode cli) on your mac? If not, type `xcode-select --install` in terminal and follow the prompts.  

<img width="651" alt="Image" src="https://github.com/user-attachments/assets/84c05cfb-52d2-4db2-af34-bc8d3a77767a" />

**Comment by chemharuka** [comment]
Tested on m2 macbook air with new installed system (15.3.1) and no other software installed.
`./toGainMapHDR ./test.tif ./ -g`
Output normal file. Bug could not reproduce.
